# Generated by Django 3.1 on 2020-09-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('USA', 'United States'), ('GER', 'Germany'), ('FRA', 'France')], max_length=10)),
                ('destination', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('USA', 'United States'), ('GER', 'Germany'), ('FRA', 'France')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('vacancy', models.PositiveIntegerField()),
                ('departure', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_passenger', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('USA', 'United States'), ('GER', 'Germany'), ('FRA', 'France')], max_length=10)),
                ('destination', models.CharField(choices=[('IND', 'India'), ('PAK', 'Pakistan'), ('USA', 'United States'), ('GER', 'Germany'), ('FRA', 'France')], max_length=10)),
                ('booked_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='AirApp.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='User.passenger')),
            ],
        ),
    ]
