# Generated by Django 3.1 on 2020-09-28 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AirApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='reach',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
